"""Initial tables

Revision ID: 8b9fd37ba0b2
Revises: 
Create Date: 2026-08-04 13:50:05.362736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9fd37ba0b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'salary',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('employees', 'joining_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('salary', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('salary', 'amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('salary', 'month',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('salary', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salary', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('salary', 'month',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('salary', 'amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('salary', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'joining_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'salary',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('attendance', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendance', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
